/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.raven.form;

import Controller.QLPhanQuyenTKController.DSTaiKhoanPhanQuyen;
import Controller.SupportFunction.StringProcessing;
import UI.BangDanhSach;
import UI.ComboboxThuong;
import Model.Accounts;
import View.AdminView.QLPhanQuyenTKView.QLPhanQuyenTKDialog.CapNhatAccountTKPhanQuyenDialog;
import View.AdminView.QLPhanQuyenTKView.QLPhanQuyenTKDialog.FilterLoaiPhanQuyenDialog;
import View.AdminView.QLPhanQuyenTKView.QLPhanQuyenTKDialog.FilterSoLanPhanQuyenTKDialog;
import View.AdminView.QLPhanQuyenTKView.QLPhanQuyenTKDialog.FilterTrangThaiPQTKDialog;
import View.AdminView.QLPhanQuyenTKView.QLPhanQuyenTKDialog.PhanQuyenTaiKhoanDialog;
import View.AdminView.QLPhanQuyenTKView.QLPhanQuyenTKDialog.SortLoaiStringPQTKDialog;
import View.AdminView.QLPhanQuyenTKView.QLPhanQuyenTKDialog.ThemTKPhanQuyenDialog;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RAVEN
 */
public class Form_3 extends javax.swing.JPanel {
     private Accounts Acc;
     public  List<Accounts> dsAccounts;    

    /**
     * Creates new form Form_1
     */
    public Form_3() {
        initComponents();
        this.dsAccounts = new DSTaiKhoanPhanQuyen().KhoiTaoListAccount();
        ShowThongTinTuDBS(BangDSPQTKChung);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TimKiemTf = new javax.swing.JTextField();
        TimKiemCb = new UI.ComboboxThuong();
        TimKiemBt = new UI.ButtonThuong();
        ThemBt = new UI.ButtonThuong();
        LamMoiBt = new UI.ButtonThuong();
        MoTKBt = new UI.ButtonThuong();
        KhoaTKBt = new UI.ButtonThuong();
        PhanQuyenBt = new UI.ButtonThuong();
        CapNhatBt = new UI.ButtonThuong();
        LocCkb = new UI.ComboboxThuong();
        SapXepCkb = new UI.ComboboxThuong();
        LocBt = new UI.ButtonThuong();
        SapXepBt = new UI.ButtonThuong();
        DangChonLbl = new javax.swing.JLabel();
        DangChonTf = new javax.swing.JTextField();
        BangSrllp = new javax.swing.JScrollPane();
        BangDSPQTKChung = new UI.BangDanhSach();

        setOpaque(false);

        TimKiemTf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TimKiemTf.setForeground(new java.awt.Color(102, 102, 102));
        TimKiemTf.setToolTipText("");
        TimKiemTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TimKiemTf.setName(""); // NOI18N

        TimKiemCb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CCCD", "Account" }));
        TimKiemCb.setSelectedItem(null
        );
        TimKiemCb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TimKiemCb.setLabeText("(Tìm kiếm theo)");
        TimKiemCb.setLineColor(new java.awt.Color(0, 153, 255));

        TimKiemBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/raven/icon/search1.png"))); // NOI18N
        TimKiemBt.setText("Tìm kiếm");
        TimKiemBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimKiemBtActionPerformed(evt);
            }
        });

        ThemBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Isert_icon.png"))); // NOI18N
        ThemBt.setText("Tạo tài khoản và phân quyền");
        ThemBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ThemBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemBtActionPerformed(evt);
            }
        });

        LamMoiBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/raven/icon/refesh.png"))); // NOI18N
        LamMoiBt.setText("Làm mới");
        LamMoiBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LamMoiBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LamMoiBtActionPerformed(evt);
            }
        });

        MoTKBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/raven/icon/unlocked.png"))); // NOI18N
        MoTKBt.setText("Mở khóa Tài khoản");
        MoTKBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoTKBtActionPerformed(evt);
            }
        });

        KhoaTKBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/raven/icon/lock.png"))); // NOI18N
        KhoaTKBt.setText("Khóa tài khoản");
        KhoaTKBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KhoaTKBtActionPerformed(evt);
            }
        });

        PhanQuyenBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/raven/icon/audience.png"))); // NOI18N
        PhanQuyenBt.setText("Phân quyền tài khoản");
        PhanQuyenBt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PhanQuyenBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhanQuyenBtActionPerformed(evt);
            }
        });

        CapNhatBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/raven/icon/edit.png"))); // NOI18N
        CapNhatBt.setText("Cập nhật thông tin tài khoản");
        CapNhatBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CapNhatBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapNhatBtActionPerformed(evt);
            }
        });

        LocCkb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Theo phân quyền", "Theo trạng thái", "Theo số lần phân quyền" }));
        LocCkb.setSelectedItem(null);
        LocCkb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LocCkb.setLabeText("(Chọn thuộc tính cần lọc)");

        SapXepCkb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Theo CCCD", "Theo Account" }));
        SapXepCkb.setSelectedItem(null);
        SapXepCkb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SapXepCkb.setLabeText("(Chọn thuộc tính cần sắp xếp)");

        LocBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/raven/icon/filter.png"))); // NOI18N
        LocBt.setText("Lọc");
        LocBt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LocBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocBtActionPerformed(evt);
            }
        });

        SapXepBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/raven/icon/sort.png"))); // NOI18N
        SapXepBt.setText("Sắp xếp");
        SapXepBt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SapXepBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SapXepBtActionPerformed(evt);
            }
        });

        DangChonLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DangChonLbl.setText("Đang chọn (Account):");

        DangChonTf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DangChonTf.setForeground(new java.awt.Color(102, 102, 102));
        DangChonTf.setText("NULL");
        DangChonTf.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        BangDSPQTKChung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CCCD", "Account", "Password", "Phân quyền", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        BangDSPQTKChung.setMaximumSize(new java.awt.Dimension(2147483647, 420));
        BangDSPQTKChung.setMinimumSize(new java.awt.Dimension(75, 420));
        BangDSPQTKChung.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        BangDSPQTKChung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BangDSPQTKChungMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BangDSPQTKChungMouseReleased(evt);
            }
        });
        BangSrllp.setViewportView(BangDSPQTKChung);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(TimKiemTf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TimKiemCb, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(MoTKBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(KhoaTKBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TimKiemBt, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(LamMoiBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ThemBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PhanQuyenBt, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SapXepCkb, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                    .addComponent(LocCkb, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LocBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SapXepBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DangChonLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DangChonTf, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CapNhatBt, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 95, Short.MAX_VALUE))
                    .addComponent(BangSrllp))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TimKiemBt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ThemBt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LocCkb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LocBt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TimKiemTf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TimKiemCb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LamMoiBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MoTKBt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KhoaTKBt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhanQuyenBt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SapXepCkb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SapXepBt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CapNhatBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DangChonLbl)
                    .addComponent(DangChonTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BangSrllp, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
public void ShowThongTinTuDBS(BangDanhSach bangDS){       
        DefaultTableModel model = (DefaultTableModel) BangDSPQTKChung.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged(); 
        
        dsAccounts = DSTaiKhoanPhanQuyen.KhoiTaoListAccount();
        
        model.setRowCount(0);    
        
        for(Accounts acc : dsAccounts){
            String PhanQuyen;
            if(acc.getPrivilege() == 0){
                PhanQuyen = "Chủ hộ";
            }else if(acc.getPrivilege() == 1){
                PhanQuyen = "Nhân viên";
            }else if(acc.getPrivilege() == 2){
                PhanQuyen = "Admin";                
            }else{
                PhanQuyen = "(Chưa phân quyền)";
            }
            String TrangThai;
            if(acc.isStatus()){
                TrangThai = "Đã bị khóa";
            }else{
                TrangThai = "Mở";
            }
            Object[] rowData = {
                acc.getCCCD(), acc.getAccount_Username(), acc.getAccount_Password(),
                PhanQuyen, TrangThai
            };

            model.addRow(rowData);
        }   
        StringProcessing.StringSortingTable(BangDSPQTKChung, 0, true);        
    }
    private void TimKiemBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimKiemBtActionPerformed
        BangDSPQTKChung.setSelectionMode(2);
        Object selected = TimKiemCb.getSelectedItem();
        if(TimKiemTf.getText().replaceAll(" ", "").equals("") || selected == null){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn loại tìm kiếm và không bỏ trống thông tin nhập!!!");
        }else if(selected.equals("CCCD")){
            if(!DSTaiKhoanPhanQuyen.Searching(TimKiemTf.getText(), BangDSPQTKChung, 1))
            JOptionPane.showMessageDialog(this, "Không tìm thấy người dùng có CCCD: " + TimKiemTf.getText());
            else
            JOptionPane.showMessageDialog(this, "Đã tìm thấy người dùng có CCCD: " + TimKiemTf.getText());
        }else if(selected.equals("Account")){
            if(!DSTaiKhoanPhanQuyen.Searching(TimKiemTf.getText(), BangDSPQTKChung, 2))
            JOptionPane.showMessageDialog(this, "Không tìm thấy người dùng có Account: " + TimKiemTf.getText());
            else
            JOptionPane.showMessageDialog(this, "Đã tìm thấy người dùng có Account: " + TimKiemTf.getText());
        }
    }//GEN-LAST:event_TimKiemBtActionPerformed

    private void ThemBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemBtActionPerformed
        showThemAccDialog();
    }//GEN-LAST:event_ThemBtActionPerformed

    private void LamMoiBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LamMoiBtActionPerformed
//        MainAdminview.setForm(new QLPhanQuyenTKMainView(MainAdminview));

         this.dsAccounts = new DSTaiKhoanPhanQuyen().KhoiTaoListAccount();
        ShowThongTinTuDBS(BangDSPQTKChung);        
    }//GEN-LAST:event_LamMoiBtActionPerformed

    private void MoTKBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoTKBtActionPerformed
        if(Acc == null){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn tài khoản cần khóa trên bảng!!!");
        }else{
            int confirm = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc muốn mở khóa tài khoản người dùng: " + Acc.getAccount_Username() + " không?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION
            );
            if (confirm == JOptionPane.YES_OPTION) {
                try{
                    DSTaiKhoanPhanQuyen.Unlock(Acc.getAccount_Username());
                    JOptionPane.showMessageDialog(this, "Đã mở khóa tài khoản người dùng có Account: " + Acc.getAccount_Username());
                    ShowThongTinTuDBS(BangDSPQTKChung);
//                    this.MainAdminview.CapNhatBangTrangThai();
                }catch(Exception e){
                    System.out.println(e);
                    JOptionPane.showMessageDialog(this, "Lỗi hệ thống!!! - Vui lòng thử lại sau", "Lỗi",
                        JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_MoTKBtActionPerformed

    private void KhoaTKBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KhoaTKBtActionPerformed
        if(Acc == null){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn tài khoản cần khóa trên bảng!!!");
        }else{
            int confirm = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc muốn khóa tài khoản người dùng: " + Acc.getAccount_Username() + " không?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION
            );
            if (confirm == JOptionPane.YES_OPTION) {
                try{
                    DSTaiKhoanPhanQuyen.Delete(Acc.getAccount_Username());
                    JOptionPane.showMessageDialog(this, "Account: " + Acc.getAccount_Username() + " đã bị khóa!");
                    ShowThongTinTuDBS(BangDSPQTKChung);
//                    this.MainAdminview.CapNhatBangTrangThai();
                }catch(Exception e){
                    System.out.println(e);
                    JOptionPane.showMessageDialog(this, "Lỗi hệ thống!!! - Vui lòng thử lại sau", "Lỗi",
                        JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_KhoaTKBtActionPerformed

    private void PhanQuyenBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhanQuyenBtActionPerformed
        if(Acc == null){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn thông tin người dùng cần phân quyền trên bảng!!!");
        }else if(Acc.getPrivilege() != -1){
            JOptionPane.showMessageDialog(this, "Tài khoản đã được phân quyền!!! - Vui lòng chọn tài khoản khác");
        }else{
            showPhanQuyenTKDialog();
        }
    }//GEN-LAST:event_PhanQuyenBtActionPerformed

    private void CapNhatBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapNhatBtActionPerformed
        if(Acc != null){
            showCapNhatAccDialog();
        }else{
            JOptionPane.showMessageDialog(this, "Vui lòng chọn thông tin người dùng cần cập nhật trên bảng!!!");
        }
    }//GEN-LAST:event_CapNhatBtActionPerformed

    private void LocBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocBtActionPerformed
        Object selected = LocCkb.getSelectedItem();
        if(selected == null){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn thuộc tính cần lọc!!!");
        }else if(selected.equals("Theo phân quyền")){
            showFilterLoaiPhanQuyenTKDialog();
        }else if(selected.equals("Theo trạng thái")){
            showFilterTrangThaiPQTKDialog();
        }else if(selected.equals("Theo số lần phân quyền")){
            showFilterSoLanPhanQuyenTKDialog();
        }
    }//GEN-LAST:event_LocBtActionPerformed

    private void SapXepBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SapXepBtActionPerformed
        Object selected = SapXepCkb.getSelectedItem();
        if(selected == null){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn thuộc tính cần sắp xếp!!!");
        }else if(selected.equals("Theo CCCD")){
            SortLoaiStringPQTKDialog sortLoaiStringPQTKDialog = new SortLoaiStringPQTKDialog(this, true);
            sortLoaiStringPQTKDialog.setVisible(true);
        }else{
            SortLoaiStringPQTKDialog sortLoaiStringPQTKDialog = new SortLoaiStringPQTKDialog( this, true);
            sortLoaiStringPQTKDialog.setVisible(true);
        }
    }//GEN-LAST:event_SapXepBtActionPerformed

    private void BangDSPQTKChungMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BangDSPQTKChungMousePressed
        int i = BangDSPQTKChung.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) BangDSPQTKChung.getModel();
        Accounts acc = DSTaiKhoanPhanQuyen.SearchObjAccount((String) model.getValueAt(i, 1));
        this.Acc = acc;
        DangChonTf.setText(Acc.getAccount_Username());
    }//GEN-LAST:event_BangDSPQTKChungMousePressed

    private void BangDSPQTKChungMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BangDSPQTKChungMouseReleased
        int i = BangDSPQTKChung.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) BangDSPQTKChung.getModel();
        Accounts acc = DSTaiKhoanPhanQuyen.SearchObjAccount((String) model.getValueAt(i, 1));
        this.Acc = acc;
        DangChonTf.setText(Acc.getAccount_Username());
    }//GEN-LAST:event_BangDSPQTKChungMouseReleased

private void showThemAccDialog() {
        ThemTKPhanQuyenDialog themTKPhanQuyenDialog = new ThemTKPhanQuyenDialog( this, true);
        themTKPhanQuyenDialog.setVisible(true);
    }

    private void showCapNhatAccDialog() {
        CapNhatAccountTKPhanQuyenDialog accountTKPhanQuyenDialog = new CapNhatAccountTKPhanQuyenDialog( this, true);
        accountTKPhanQuyenDialog.setVisible(true);
    }    
    
    private void showPhanQuyenTKDialog() {
        PhanQuyenTaiKhoanDialog phanQuyenTaiKhoanDialog = new PhanQuyenTaiKhoanDialog( this, true);
        phanQuyenTaiKhoanDialog.setVisible(true);
    }    
    
    private void showFilterLoaiPhanQuyenTKDialog() {
        FilterLoaiPhanQuyenDialog filterLoaiPhanQuyenDialog = new FilterLoaiPhanQuyenDialog( this, true);
        filterLoaiPhanQuyenDialog.setVisible(true);
    }    

    private void showFilterTrangThaiPQTKDialog() {
        FilterTrangThaiPQTKDialog filterTrangThaiPQTKDialog = new FilterTrangThaiPQTKDialog( this, true);
        filterTrangThaiPQTKDialog.setVisible(true);
    }   
    
    private void showFilterSoLanPhanQuyenTKDialog() {
        FilterSoLanPhanQuyenTKDialog filterSoLanPhanQuyenTKDialog = new FilterSoLanPhanQuyenTKDialog( this, true);
        filterSoLanPhanQuyenTKDialog.setVisible(true);
    } 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private UI.BangDanhSach BangDSPQTKChung;
    private javax.swing.JScrollPane BangSrllp;
    private UI.ButtonThuong CapNhatBt;
    private javax.swing.JLabel DangChonLbl;
    private javax.swing.JTextField DangChonTf;
    private UI.ButtonThuong KhoaTKBt;
    private UI.ButtonThuong LamMoiBt;
    private UI.ButtonThuong LocBt;
    private UI.ComboboxThuong LocCkb;
    private UI.ButtonThuong MoTKBt;
    private UI.ButtonThuong PhanQuyenBt;
    private UI.ButtonThuong SapXepBt;
    private UI.ComboboxThuong SapXepCkb;
    private UI.ButtonThuong ThemBt;
    private UI.ButtonThuong TimKiemBt;
    private UI.ComboboxThuong TimKiemCb;
    private javax.swing.JTextField TimKiemTf;
    // End of variables declaration//GEN-END:variables
 public BangDanhSach getBangDSPQTKChung() {
        return BangDSPQTKChung;
    }

    public void setBangDSPQTKChung(BangDanhSach BangDSPQTKChung) {
        this.BangDSPQTKChung = BangDSPQTKChung;
    }
    
    public Accounts getAcc() {
        return Acc;
    }

    public void setAcc(Accounts Acc) {
        this.Acc = Acc;
    }

    public ComboboxThuong getSapXepCkb() {
        return SapXepCkb;
    }

    public void setSapXepCkb(ComboboxThuong SapXepCkb) {
        this.SapXepCkb = SapXepCkb;
    }
}
