/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package mainNV.raven.form;

import Controller.DAO.W_MeterDetailDAO;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Map;
import javax.swing.JOptionPane;
import login.raven.component.PanelLoginAndRegister;

/**
 *
 * @author DELL
 */
public class JDialogGhiSoNuoc extends javax.swing.JDialog {
    private String _date;
    private int _idStaff;
    
    /**
     * Creates new form JDialogGhiSoNuoc
     */
    public JDialogGhiSoNuoc(boolean modal) {
       // super(parent, modal);
        initComponents();
         setLocationRelativeTo(null);
          SimpleDateFormat sp = new SimpleDateFormat("yyyy-MM-dd");
    Date date =new Date();
     String datestr=sp.format(date);
         datestr =new W_MeterDetailDAO().convertngay(datestr);
         _date=datestr;
         txtDate.setText(_date);
          _idStaff=PanelLoginAndRegister._idStaff;
         //   System.out.println("id staff" + PanelLoginAndRegister._idStaff);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnGhi = new javax.swing.JButton();
        txtDate = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtChuHo = new javax.swing.JTextField();
        txtSoNuocCu = new javax.swing.JTextField();
        txtSoNuocMoi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCongTo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("GHI SỐ NƯỚC");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel1)
                .addContainerGap(221, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(16, 16, 16))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("THÁNG :");

        jLabel3.setText("CHỦ HỘ");

        jLabel4.setText("SỐ NƯỚC CŨ:");

        btnGhi.setText("Ghi");
        btnGhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiActionPerformed(evt);
            }
        });

        jLabel7.setText("SỐ NƯỚC MỚI");

        txtChuHo.setEditable(false);

        txtSoNuocCu.setEditable(false);

        jLabel5.setText("ID_CongTo");

        txtCongTo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCongToFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGhi, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)))
                            .addComponent(jLabel5))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtSoNuocMoi, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(txtSoNuocCu)
                            .addComponent(txtCongTo)))
                    .addComponent(txtChuHo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDate))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCongTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtChuHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSoNuocCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoNuocMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(btnGhi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiActionPerformed
        // TODO add your handling code here:
        
       
        W_MeterDetailDAO hdd = new W_MeterDetailDAO();
    

            String sonuoccu = txtSoNuocCu.getText().trim();
            String sonuocmoi = txtSoNuocMoi.getText().trim();
            int sonuocmoiINT= Integer.valueOf(sonuocmoi);

            String kiemtraso = "^[0-9.+]+$";
            if (!hdd.checkExistWMetter(txtCongTo.getText())) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy Công tơ nước!");
            } 

             else if (sonuocmoi.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không được để trống số nước. Vui lòng nhập lại!");
            }
            else if (!sonuoccu.matches(kiemtraso)) {
                JOptionPane.showMessageDialog(this, "Định dạng số nước sai. Vui lòng nhập lại!");
            } else if (!sonuocmoi.matches(kiemtraso)) {
                JOptionPane.showMessageDialog(this, "Định dạng số nước sai. Vui lòng nhập lại!");
            }  else {

              
                float sonuoccuf = Float.parseFloat(txtSoNuocCu.getText().trim());
                float sonuocmoif = Float.parseFloat(txtSoNuocMoi.getText().trim());

                if (sonuocmoif < sonuoccuf) {
                    JOptionPane.showMessageDialog(this, "Số nước mới không thể thấp hơn số nước cũ. Vui lòng nhập lại!");
                } else {
                    int test = JOptionPane.showConfirmDialog(null, "Bạn chắc có muốn thêm số điện nước hay không?", "Thông báo", JOptionPane.YES_NO_OPTION);
                    if (test == JOptionPane.YES_OPTION) {
//                        AddDichVu();
//                        AddHoaDonPhong();
//                        CapNhatDichVuPhong();
//                        showTable();
                    
//                        hdd.addBangSDNuoc(date_, txtChuHo.getText(), txtSoNuocCu.getText().trim(), txtSoNuocMoi.getText().trim());
//                        hdd.addHoaDonNuoc(date_, txtChuHo.getText(), txtSoNuocCu.getText().trim(), txtSoNuocMoi.getText().trim());
                           hdd.AddWmetter(txtCongTo.getText(),sonuocmoiINT,_idStaff,_date);
                           this.dispose();
                    } else if (test == JOptionPane.NO_OPTION) {
                        JOptionPane.showMessageDialog(this, "Bạn đã hủy cập nhật thành công");
                    }
                }
            }
        
        
        
    }//GEN-LAST:event_btnGhiActionPerformed

    private void txtCongToFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCongToFocusLost
        // TODO add your handling code here:
     
         W_MeterDetailDAO wmtd= new W_MeterDetailDAO();
         if (!wmtd.checkIdStaff(_idStaff, txtCongTo.getText())) {
                JOptionPane.showMessageDialog(this, "Công tơ này không thuộc quyền quản lý của bạn!");
            }
         else if (wmtd.checkExistWMDetail(txtCongTo.getText(), _date)) {
                JOptionPane.showMessageDialog(this, "Số nước tháng này của công tơ đã được ghi!");
            }
         else{
         
            SimpleDateFormat dateFormat1 = new SimpleDateFormat("yyyy-MM-dd");
      //  String thangnay=dateFormat1.format(ps.getCreating_Date());
        String cccd=wmtd.getCCCDByIDMeter(txtCongTo.getText());
        String hoten =wmtd.getHotenByCCCD(cccd);
        txtChuHo.setText(hoten);
        String thangcu = wmtd.thangnuoccu(_date);
        int sonuoccu=wmtd.getSonuoccu(thangcu,txtCongTo.getText());
        txtSoNuocCu.setText(String.valueOf(sonuoccu));
        String address= wmtd.getaddressByIdmeter(txtCongTo.getText());
         }
        
        
    }//GEN-LAST:event_txtCongToFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogGhiSoNuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogGhiSoNuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogGhiSoNuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogGhiSoNuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogGhiSoNuoc dialog = new JDialogGhiSoNuoc(true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGhi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtChuHo;
    private javax.swing.JTextField txtCongTo;
    private javax.swing.JLabel txtDate;
    private javax.swing.JTextField txtSoNuocCu;
    private javax.swing.JTextField txtSoNuocMoi;
    // End of variables declaration//GEN-END:variables

//    public void setData(Map data)
//    {
//        txtDate.setText((String) data.get("thangghi"));
//        date_=(String) data.get("thangghi1");
//      //  System.out.println("ngay2 set data"+(String) data.get("thangghi1"));
//    }
}
