/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mainCH.raven.form;

/**
 *
 * @author DELL
 */
public class KhoanPhi extends javax.swing.JPanel {

    /**
     * Creates new form KhoanPhi
     */
    public KhoanPhi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        quanLyDienNuoc1 = new main.raven.form.QuanLyNuoc();
        jpanelQuanLyTienPhong1 = new main.raven.form.JpanelQuanLyTienPhong();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(980, 670));

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(915, 524));
        jTabbedPane1.addTab("QUẢN LÝ NƯỚC", quanLyDienNuoc1);
        jTabbedPane1.addTab("QUẢN LÝ HÓA ĐƠN", jpanelQuanLyTienPhong1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, Short.MAX_VALUE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("QUẢN LÝ NƯỚC");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private main.raven.form.JpanelQuanLyTienPhong jpanelQuanLyTienPhong1;
    private main.raven.form.QuanLyNuoc quanLyDienNuoc1;
    // End of variables declaration//GEN-END:variables
}
